# Generated by Django 3.2.14 on 2022-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('waste_name', models.CharField(max_length=32, verbose_name='垃圾名称')),
                ('image', models.CharField(max_length=255, null=True, verbose_name='垃圾图片')),
                ('classification_id', models.IntegerField(verbose_name='分类ID')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '垃圾',
                'verbose_name_plural': '垃圾',
                'db_table': 'tb_waste',
            },
        ),
    ]
