# Generated by Django 3.2.14 on 2023-10-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_waste_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='category_id',
            new_name='classification_id',
        ),
    ]
