# Generated by Django 3.2.14 on 2022-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('category_name', models.CharField(max_length=16, verbose_name='分类名称')),
                ('icon', models.CharField(max_length=255, verbose_name='分类图标')),
                ('description', models.TextField(verbose_name='分类介绍')),
                ('regulation', models.TextField(verbose_name='投放规定')),
                ('include', models.TextField(verbose_name='主要包括哪些垃圾')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'tb_category',
            },
        ),
    ]
