# Generated by Django 3.2.14 on 2022-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=255, null=True, verbose_name='分类图标'),
        ),
    ]
